# Generated by Django 4.1.4 on 2024-04-02 18:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='session_attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee', models.CharField(max_length=20)),
                ('dateofvisit', models.DateField(default=datetime.date(2024, 4, 2), verbose_name='Date:')),
                ('session_attended', models.CharField(blank=True, choices=[('FaithKids 1st Service', 'FaithKids 1st Service'), ('FaithKids 2nd Service', 'FaithKids 2nd Service'), ('Big Church 1st Service', 'Big Church 1st Service'), ('Big Church 2nd Service', 'Big Church 2nd Service'), ('Ylife', 'Ylife')], max_length=30)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
