# Generated by Django 4.2.15 on 2024-09-17 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='session_attended_options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_attended', models.CharField(max_length=30)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('group_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='session_attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateofvisit', models.DateField(default=django.utils.timezone.now, verbose_name='Date:')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('attendee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.people')),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session_attended', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.session_attended_options', verbose_name='Meeting:')),
            ],
        ),
        migrations.CreateModel(
            name='session_absent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateofmeeting', models.DateField(default=django.utils.timezone.now, verbose_name='Date:')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('follow_up_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date:')),
                ('follow_up_Feedback', models.TextField(blank=True, null=True, verbose_name='Feedback:')),
                ('absentee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.people')),
                ('session_missed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.session_attended_options')),
            ],
        ),
        migrations.CreateModel(
            name='prayer_cell_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_meeting', models.DateField(verbose_name='Date of meeting:')),
                ('word_discussed', models.TextField(verbose_name='Word Discussed:')),
                ('prayed_about', models.TextField(verbose_name='Prayed About:')),
                ('testimonies', models.TextField(blank=True, null=True, verbose_name='Testimonies:')),
                ('prayer_requests', models.TextField(blank=True, null=True, verbose_name='Prayer Requests')),
                ('disciple_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.people')),
                ('meeting_hosted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.session_attended_options')),
            ],
        ),
        migrations.CreateModel(
            name='group_membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.session_attended_options')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.people')),
            ],
        ),
        migrations.AddConstraint(
            model_name='session_attendance',
            constraint=models.UniqueConstraint(fields=('attendee', 'dateofvisit', 'session_attended'), name='groups_session_attendance_unique'),
        ),
        migrations.AddConstraint(
            model_name='session_absent',
            constraint=models.UniqueConstraint(fields=('absentee', 'dateofmeeting', 'session_missed'), name='groups_session_absent_unique'),
        ),
        migrations.AddConstraint(
            model_name='group_membership',
            constraint=models.UniqueConstraint(fields=('member', 'group'), name='groups_group_membership_unique'),
        ),
    ]
