# Generated by Django 4.2.15 on 2024-09-18 21:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='leaving_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_withdrew', models.DateField(default=django.utils.timezone.now, verbose_name='Date:')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('reason_leaving', models.TextField(blank=True, null=True, verbose_name='Feedback:')),
                ('member_leaving', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.people')),
            ],
        ),
    ]
