# Generated by Django 4.1.4 on 2024-04-08 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0002_alter_session_attendance_attendee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_attendance',
            name='attendee',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='session_attendance',
            name='createdby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='session_attendance',
            name='creation_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='session_attendance',
            name='session_attended',
            field=models.CharField(choices=[('FaithKids 1st Service', 'FaithKids 1st Service'), ('FaithKids 2nd Service', 'FaithKids 2nd Service'), ('Big Church 1st Service', 'Big Church 1st Service'), ('Big Church 2nd Service', 'Big Church 2nd Service'), ('Ylife', 'Ylife')], max_length=30),
        ),
    ]
