# Generated by Django 4.2.15 on 2024-09-21 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_leaving_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_attendance',
            name='session_attended',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.session_attended_options', verbose_name='Group:'),
        ),
        migrations.AddConstraint(
            model_name='prayer_cell_feedback',
            constraint=models.UniqueConstraint(fields=('date_of_meeting', 'meeting_hosted'), name='groups_prayer_cell_feedback_unique'),
        ),
    ]
