# Generated by Django 4.1.4 on 2024-04-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_session_attendance_attendee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_attendance',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
