# Generated by Django 4.1.4 on 2024-04-08 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0004_alter_session_attendance_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_attendance',
            name='createdby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='session_attendance',
            name='session_attended',
            field=models.CharField(blank=True, choices=[('FaithKids 1st Service', 'FaithKids 1st Service'), ('FaithKids 2nd Service', 'FaithKids 2nd Service'), ('Big Church 1st Service', 'Big Church 1st Service'), ('Big Church 2nd Service', 'Big Church 2nd Service'), ('Ylife', 'Ylife')], max_length=30),
        ),
    ]
