# Generated by Django 4.1.4 on 2024-04-08 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_alter_session_attendance_createdby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_attendance',
            name='attendee',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='session_attendance',
            name='dateofvisit',
            field=models.DateField(default=datetime.date(2024, 4, 9), verbose_name='Date:'),
        ),
    ]
