# Generated by Django 4.1.4 on 2024-04-15 19:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('groups', '0007_alter_session_attendance_createdby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_attendance',
            name='attendee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.people'),
        ),
        migrations.AlterField(
            model_name='session_attendance',
            name='dateofvisit',
            field=models.DateField(default=datetime.date(2024, 4, 15), verbose_name='Date:'),
        ),
    ]
