# Generated by Django 4.1.4 on 2024-04-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_alter_session_attendance_attendee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_attendance',
            name='attendee',
            field=models.CharField(max_length=100),
        ),
    ]
