# Generated by Django 4.1.4 on 2024-04-20 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_alter_session_attendance_attendee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_attendance',
            name='dateofvisit',
            field=models.DateField(default=datetime.date(2024, 4, 20), verbose_name='Date:'),
        ),
        migrations.AddConstraint(
            model_name='session_attendance',
            constraint=models.UniqueConstraint(fields=('attendee', 'dateofvisit', 'session_attended'), name='groups_session_attendance_unique'),
        ),
    ]
