# Generated by Django 4.1.4 on 2024-04-25 20:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0011_alter_session_attendance_dateofvisit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_attendance',
            name='dateofvisit',
            field=models.DateField(default=datetime.date(2024, 4, 25), verbose_name='Date:'),
        ),
        migrations.CreateModel(
            name='session_attended_options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_attended', models.CharField(choices=[('FaithKids 1st Service', 'FaithKids 1st Service'), ('FaithKids 2nd Service', 'FaithKids 2nd Service'), ('Big Church 1st Service', 'Big Church 1st Service'), ('Big Church 2nd Service', 'Big Church 2nd Service'), ('Ylife', 'Ylife')], max_length=30)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
