# Generated by Django 4.1.4 on 2024-05-03 20:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0012_alter_session_attendance_dateofvisit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_attendance',
            name='dateofvisit',
            field=models.DateField(default=datetime.date(2024, 5, 3), verbose_name='Date:'),
        ),
        migrations.AlterField(
            model_name='session_attendance',
            name='session_attended',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.session_attended_options'),
        ),
        migrations.AlterField(
            model_name='session_attended_options',
            name='session_attended',
            field=models.CharField(choices=[('1', 'FaithKids 1st Service'), ('2', 'FaithKids 2nd Service'), ('3', 'Big Church 1st Service'), ('4', 'Big Church 2nd Service'), ('5', 'Ylife')], max_length=30),
        ),
    ]
