# Generated by Django 4.1.4 on 2024-05-12 19:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('groups', '0013_alter_session_attendance_dateofvisit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_attendance',
            name='dateofvisit',
            field=models.DateField(default=datetime.date(2024, 5, 12), verbose_name='Date:'),
        ),
        migrations.CreateModel(
            name='group_membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.session_attended_options')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.people')),
            ],
        ),
        migrations.AddConstraint(
            model_name='group_membership',
            constraint=models.UniqueConstraint(fields=('member', 'group'), name='groups_group_membership_unique'),
        ),
    ]
