# Generated by Django 4.1.4 on 2024-05-29 21:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('groups', '0014_alter_session_attendance_dateofvisit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_attendance',
            name='dateofvisit',
            field=models.DateField(default=datetime.date(2024, 5, 29), verbose_name='Date:'),
        ),
        migrations.CreateModel(
            name='prayer_cell_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_meeting', models.DateField(verbose_name='Date of meeting:')),
                ('word_discussed', models.TextField(verbose_name='Word Discussed:')),
                ('prayed_about', models.TextField(verbose_name='Prayed About:')),
                ('testimonys', models.TextField(verbose_name='Testimonies:')),
                ('prayer_requests', models.TextField(verbose_name='Prayer Requests')),
                ('disciple_leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.people')),
            ],
        ),
    ]
