# Generated by Django 4.1.4 on 2024-05-29 23:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0015_alter_session_attendance_dateofvisit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prayer_cell_feedback',
            name='testimonys',
        ),
        migrations.AddField(
            model_name='prayer_cell_feedback',
            name='testimonies',
            field=models.CharField(default='2024\t\x01', max_length=30, verbose_name='Testimonies:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prayer_cell_feedback',
            name='prayed_about',
            field=models.CharField(max_length=30, verbose_name='Prayed About:'),
        ),
        migrations.AlterField(
            model_name='prayer_cell_feedback',
            name='prayer_requests',
            field=models.CharField(max_length=30, verbose_name='Prayer Requests'),
        ),
        migrations.AlterField(
            model_name='prayer_cell_feedback',
            name='word_discussed',
            field=models.CharField(max_length=30, verbose_name='Word Discussed:'),
        ),
        migrations.AlterField(
            model_name='session_attendance',
            name='dateofvisit',
            field=models.DateField(default=datetime.date(2024, 5, 30), verbose_name='Date:'),
        ),
    ]
