# Generated by Django 4.1.4 on 2024-06-07 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0016_remove_prayer_cell_feedback_testimonys_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session_attended_options',
            old_name='createdby',
            new_name='group_leader',
        ),
        migrations.AlterField(
            model_name='session_attendance',
            name='dateofvisit',
            field=models.DateField(default=datetime.date(2024, 6, 7), verbose_name='Date:'),
        ),
    ]
