# Generated by Django 4.1.4 on 2024-06-11 19:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0017_rename_createdby_session_attended_options_group_leader_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayer_cell_feedback',
            name='meeting_hosted',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.session_attended_options'),
        ),
        migrations.AlterField(
            model_name='session_attendance',
            name='dateofvisit',
            field=models.DateField(default=datetime.date(2024, 6, 11), verbose_name='Date:'),
        ),
    ]
