# Generated by Django 4.1.4 on 2024-06-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0018_prayer_cell_feedback_meeting_hosted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayer_cell_feedback',
            name='prayed_about',
            field=models.TextField(max_length=30, verbose_name='Prayed About:'),
        ),
        migrations.AlterField(
            model_name='prayer_cell_feedback',
            name='prayer_requests',
            field=models.TextField(max_length=30, verbose_name='Prayer Requests'),
        ),
        migrations.AlterField(
            model_name='prayer_cell_feedback',
            name='testimonies',
            field=models.TextField(max_length=30, verbose_name='Testimonies:'),
        ),
        migrations.AlterField(
            model_name='prayer_cell_feedback',
            name='word_discussed',
            field=models.TextField(max_length=30, verbose_name='Word Discussed:'),
        ),
    ]
