# Generated by Django 4.1.4 on 2024-06-11 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('groups', '0020_alter_prayer_cell_feedback_prayed_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayer_cell_feedback',
            name='disciple_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.people'),
        ),
        migrations.AlterField(
            model_name='prayer_cell_feedback',
            name='meeting_hosted',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.session_attended_options'),
        ),
    ]
