# Generated by Django 4.1.4 on 2024-06-22 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0021_alter_prayer_cell_feedback_disciple_leader_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayer_cell_feedback',
            name='prayer_requests',
            field=models.TextField(null=True, verbose_name='Prayer Requests'),
        ),
        migrations.AlterField(
            model_name='prayer_cell_feedback',
            name='testimonies',
            field=models.TextField(null=True, verbose_name='Testimonies:'),
        ),
        migrations.AlterField(
            model_name='session_attendance',
            name='dateofvisit',
            field=models.DateField(default=datetime.date(2024, 6, 22), verbose_name='Date:'),
        ),
    ]
