# Generated by Django 4.1.4 on 2024-06-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0022_alter_prayer_cell_feedback_prayer_requests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayer_cell_feedback',
            name='prayer_requests',
            field=models.TextField(blank=True, null=True, verbose_name='Prayer Requests'),
        ),
        migrations.AlterField(
            model_name='prayer_cell_feedback',
            name='testimonies',
            field=models.TextField(blank=True, null=True, verbose_name='Testimonies:'),
        ),
    ]
