# Generated by Django 4.1.4 on 2024-07-06 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0023_alter_prayer_cell_feedback_prayer_requests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_attendance',
            name='dateofvisit',
            field=models.DateField(default=datetime.date(2024, 7, 6), verbose_name='Date:'),
        ),
    ]
