# Generated by Django 5.0.7 on 2024-07-21 20:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0024_alter_session_attendance_dateofvisit'),
        ('people', '0003_rename_guardian_guardianrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_attendance',
            name='dateofvisit',
            field=models.DateField(default=datetime.date(2024, 7, 21), verbose_name='Date:'),
        ),
        migrations.CreateModel(
            name='session_absent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateofmeeting', models.DateField(default=datetime.date(2024, 7, 21), verbose_name='Date:')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('absentee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.people')),
                ('session_missed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.session_attended_options')),
            ],
        ),
        migrations.AddConstraint(
            model_name='session_absent',
            constraint=models.UniqueConstraint(fields=('absentee', 'dateofmeeting', 'session_missed'), name='groups_session_absent_unique'),
        ),
    ]
