# Generated by Django 5.0.7 on 2024-07-30 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0026_alter_session_absent_dateofmeeting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_absent',
            name='follow_up_Feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Feedback:'),
        ),
        migrations.AddField(
            model_name='session_absent',
            name='follow_up_date',
            field=models.DateField(default=datetime.date(2024, 7, 30), verbose_name='Date:'),
        ),
        migrations.AlterField(
            model_name='session_absent',
            name='dateofmeeting',
            field=models.DateField(default=datetime.date(2024, 7, 30), verbose_name='Date:'),
        ),
        migrations.AlterField(
            model_name='session_attendance',
            name='dateofvisit',
            field=models.DateField(default=datetime.date(2024, 7, 30), verbose_name='Date:'),
        ),
    ]
