# Generated by Django 5.0.7 on 2024-08-20 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0027_session_absent_follow_up_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_absent',
            name='dateofmeeting',
            field=models.DateField(default=datetime.date(2024, 8, 20), verbose_name='Date:'),
        ),
        migrations.AlterField(
            model_name='session_absent',
            name='follow_up_date',
            field=models.DateField(default=datetime.date(2024, 8, 20), verbose_name='Date:'),
        ),
        migrations.AlterField(
            model_name='session_attendance',
            name='dateofvisit',
            field=models.DateField(default=datetime.date(2024, 8, 20), verbose_name='Date:'),
        ),
        migrations.AlterField(
            model_name='session_attended_options',
            name='session_attended',
            field=models.CharField(max_length=30),
        ),
    ]
