
version: "3.8"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: ["sh", "./start.sh"]
    volumes:
      - .:/dockerapp
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: {}