# Generated by Django 4.2.15 on 2024-09-17 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Converts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Surname', models.CharField(max_length=20)),
                ('Gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=7)),
                ('CellNumber', models.CharField(blank=True, max_length=10)),
                ('EmailAddress', models.EmailField(blank=True, max_length=50)),
                ('whereConverted', models.CharField(blank=True, choices=[('FaithKids', 'FaithKids'), ('Online', 'Online'), ('Outreach', 'Outreach'), ('RSCFC Auditorium', 'RSCFC Auditorium'), ('Ylife', 'Ylife')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('area', models.CharField(blank=True, max_length=20)),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Followups',
            fields=[
                ('convert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='SalvationFollowUps.converts')),
                ('Language', models.CharField(blank=True, choices=[('African', 'African'), ('Afrikaans', 'Afrikaans'), ('English', 'English')], max_length=20)),
                ('AttendChurch', models.CharField(choices=[('Unkown', 'Unkown'), ('RSCFC', 'RSCFC'), ('Local No', 'Local No'), ('Another Church', 'Another Church'), ('Away: want to be connected', 'Away: want to be connected'), ('Connected', 'Connected')], default='Unknown', max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('next_followUpdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_followUpdate'],
            },
        ),
        migrations.CreateModel(
            name='salvations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateofcommitment', models.DateField(default=django.utils.timezone.now, verbose_name='Date:')),
                ('contactMethod', models.CharField(choices=[('Phone', 'Phone'), ('Email', 'Email')], default='Unspecified', max_length=20)),
                ('decissionType', models.CharField(choices=[('First Time', 'First Time'), ('Rededication', 'Rededication')], default='Unspecified', max_length=20)),
                ('convert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.people')),
            ],
            options={
                'verbose_name_plural': 'Salvations',
            },
        ),
        migrations.CreateModel(
            name='Link_Church',
            fields=[
                ('convert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='SalvationFollowUps.followups')),
                ('church_name', models.CharField(choices=[('Rhema Randburg', 'Rhema Randburg'), ('Rhema South', 'Rhema South')], max_length=40)),
                ('church_area', models.CharField(blank=True, max_length=20)),
                ('church_phone_number', models.CharField(blank=True, max_length=10)),
                ('church_contact_name', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Requests_Feedback',
            fields=[
                ('convert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='SalvationFollowUps.converts')),
                ('PrayerRequest', models.CharField(blank=True, max_length=200)),
                ('General', models.CharField(blank=True, max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Prayer Requests & Feedback',
            },
        ),
        migrations.CreateModel(
            name='Followed_Up_by',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('convert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SalvationFollowUps.followups')),
            ],
        ),
        migrations.AddConstraint(
            model_name='converts',
            constraint=models.UniqueConstraint(fields=('Name', 'Surname'), name='salvationfollowups_converts_unique'),
        ),
        migrations.AddField(
            model_name='link_church',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
