# Generated by Django 4.2.15 on 2024-09-28 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SalvationFollowUps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_convert_followup_call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_feedback', models.TextField(verbose_name='Feedback:')),
                ('prayer_request', models.TextField(blank=True, null=True, verbose_name='Prayer Request')),
                ('date_of_followup', models.DateField(default=django.utils.timezone.now, verbose_name='Date:')),
                ('convert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SalvationFollowUps.salvations')),
                ('followedup_up_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'New Convert Follow up',
            },
        ),
        migrations.CreateModel(
            name='new_convert_first_followup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_of_followup', models.CharField(choices=[('Whatsapp', 'Whatsapp'), ('Email', 'Email')], default='Unspecified', max_length=20)),
                ('response', models.TextField(blank=True, null=True, verbose_name='Response:')),
                ('added_to_Whatsapp_group', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=5)),
                ('date_of_followup', models.DateField(default=django.utils.timezone.now, verbose_name='Date:')),
                ('convert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SalvationFollowUps.salvations')),
                ('followedup_up_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'New Convert First Follow up',
            },
        ),
    ]
