# Generated by Django 4.1.4 on 2023-01-04 13:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SalvationFollowUps', '0002_alter_followups_next_followupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followups',
            name='AttendChurch',
            field=models.CharField(choices=[('Unkown', 'Unkown'), ('RSCFC', 'RSCFC'), ('Local No', 'Local No'), ('Another Church', 'Another Church'), ('Away: want to be connected', 'Away: want to be connected'), ('Connected', 'Connected')], default='Unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='followups',
            name='next_followUpdate',
            field=models.DateTimeField(default=datetime.date(2023, 1, 4)),
        ),
        migrations.CreateModel(
            name='Followed_Up_by',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SalvationFollowUps.followups')),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
