# Generated by Django 4.2.15 on 2024-10-03 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_prayer_cell_feedback_disciple_leader'),
        ('SalvationFollowUps', '0003_new_convert_referral_finalize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_convert_referral_finalize',
            name='refer_to_church',
            field=models.TextField(blank=True, null=True, verbose_name='Refer to another church:'),
        ),
        migrations.AlterField(
            model_name='new_convert_referral_finalize',
            name='refer_to_prayer_cell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.session_attended_options'),
        ),
    ]
