# Generated by Django 4.1.4 on 2023-01-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalvationFollowUps', '0003_alter_followups_attendchurch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followed_up_by',
            name='convert',
        ),
        migrations.AddField(
            model_name='followed_up_by',
            name='convert',
            field=models.ManyToManyField(to='SalvationFollowUps.followups'),
        ),
    ]
