# Generated by Django 4.1.4 on 2023-01-04 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SalvationFollowUps', '0004_remove_followed_up_by_convert_followed_up_by_convert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followed_up_by',
            name='convert',
        ),
        migrations.AddField(
            model_name='followed_up_by',
            name='convert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SalvationFollowUps.followups'),
        ),
    ]
