# Generated by Django 4.2.15 on 2024-10-03 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_prayer_cell_feedback_disciple_leader'),
        ('SalvationFollowUps', '0005_alter_new_convert_referral_finalize_refer_to_prayer_cell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_convert_referral_finalize',
            name='refer_to_prayer_cell',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.session_attended_options'),
        ),
    ]
