# Generated by Django 4.1.4 on 2023-01-04 20:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SalvationFollowUps', '0005_remove_followed_up_by_convert_followed_up_by_convert'),
    ]

    operations = [
        migrations.AddField(
            model_name='followed_up_by',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
