# Generated by Django 4.1.4 on 2023-01-06 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalvationFollowUps', '0006_followed_up_by_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='converts',
            name='whereConverted',
            field=models.CharField(blank=True, choices=[('FaithKids', 'FaithKids'), ('Online', 'Online'), ('Outreach', 'Outreach'), ('RSCFC Auditorium', 'RSCFC Auditorium'), ('Ylife', 'Ylife')], max_length=20),
        ),
        migrations.AlterField(
            model_name='followups',
            name='next_followUpdate',
            field=models.DateTimeField(default=datetime.date(2023, 1, 6)),
        ),
    ]
