# Generated by Django 4.1.4 on 2024-03-23 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalvationFollowUps', '0007_alter_converts_whereconverted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='converts',
            options={},
        ),
        migrations.AlterField(
            model_name='converts',
            name='Name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='converts',
            name='Surname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='followups',
            name='next_followUpdate',
            field=models.DateTimeField(default=datetime.date(2024, 3, 23)),
        ),
        migrations.AddConstraint(
            model_name='converts',
            constraint=models.UniqueConstraint(fields=('Name', 'Surname'), name='salvationfollowups_converts_unique'),
        ),
    ]
