# Generated by Django 4.2.15 on 2024-11-05 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campuses', '0001_initial'),
        ('SalvationFollowUps', '0007_alter_new_convert_referral_finalize_refer_to_prayer_cell'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_convert_referral_finalize',
            name='refer_to_campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campuses.campuses_details'),
        ),
    ]
