# Generated by Django 4.1.4 on 2024-03-28 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalvationFollowUps', '0008_alter_converts_options_alter_converts_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followups',
            name='next_followUpdate',
            field=models.DateTimeField(default=datetime.date(2024, 3, 28)),
        ),
    ]
