# Generated by Django 4.1.4 on 2024-04-08 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalvationFollowUps', '0012_alter_followups_next_followupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followups',
            name='next_followUpdate',
            field=models.DateTimeField(default=datetime.date(2024, 4, 9)),
        ),
    ]
