# Generated by Django 5.0.7 on 2024-08-20 16:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalvationFollowUps', '0028_alter_followups_next_followupdate'),
        ('people', '0004_alter_guardianrelation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followups',
            name='next_followUpdate',
            field=models.DateTimeField(default=datetime.date(2024, 8, 20)),
        ),
        migrations.CreateModel(
            name='salvations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateofcommitment', models.DateField(default=datetime.date(2024, 8, 20), verbose_name='Date:')),
                ('contactMethod', models.CharField(choices=[('Phone', 'Phone'), ('Email', 'Email')], default='Unspecified', max_length=20)),
                ('decissionType', models.CharField(choices=[('First Time', 'First Time'), ('Rededication', 'Rededication')], default='Unspecified', max_length=20)),
                ('convert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.people')),
            ],
            options={
                'verbose_name_plural': 'Salvations',
            },
        ),
    ]
