# Generated by Django 4.2.15 on 2024-11-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_childrenschurch_class_member_childrenschurch_classes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_attendance',
            name='service',
            field=models.CharField(choices=[('1', '1st Service'), ('2', '2nd Service')], max_length=3),
        ),
    ]
