# Generated by Django 4.2.15 on 2024-11-12 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0003_alter_class_attendance_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='transport_ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=20)),
                ('passenger_assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='trip_passengers_absent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateoftrip', models.DateField(default=django.utils.timezone.now, verbose_name='Date:')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('follow_up_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date:')),
                ('follow_up_Feedback', models.TextField(blank=True, null=True, verbose_name='Feedback:')),
                ('absentee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.people')),
                ('transport_opp_missed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.transport_ministry')),
            ],
        ),
        migrations.CreateModel(
            name='trip_passengers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateoftrip', models.DateField(default=django.utils.timezone.now, verbose_name='Date:')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('area_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.transport_ministry')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.people')),
            ],
        ),
        migrations.CreateModel(
            name='transport_passengers_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('bus_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.transport_ministry')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.people')),
            ],
        ),
    ]
