# Generated by Django 4.2.15 on 2024-10-20 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='campuses_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_name', models.CharField(blank=True, max_length=30, null=True)),
                ('campus_area', models.CharField(blank=True, max_length=30, null=True)),
                ('campus_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('overseer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overseer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='campus_meetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_type', models.CharField(max_length=30, verbose_name='Service Type:')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('dateofmeeting', models.DateField(default=django.utils.timezone.now, verbose_name='Date:')),
                ('children_attending', models.CharField(blank=True, max_length=8, null=True)),
                ('adults_attending', models.CharField(blank=True, max_length=8, null=True)),
                ('salvations', models.CharField(blank=True, max_length=8, null=True)),
                ('general_feedback', models.TextField(blank=True, null=True, verbose_name='Feedback:')),
                ('campus_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
