# Generated by Django 4.1.4 on 2023-01-06 14:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SalvationFollowUps', '0007_alter_converts_whereconverted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='visit_date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateofvisit', models.DateTimeField(default=datetime.date(2023, 1, 6))),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('visitor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='SalvationFollowUps.converts')),
            ],
        ),
    ]
