# Generated by Django 4.2.15 on 2024-10-11 22:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='visit_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateofvisit', models.DateField(default=django.utils.timezone.now, verbose_name='Date:')),
                ('contactMethod', models.CharField(choices=[('Phone', 'Phone'), ('Email', 'Email')], default='Unspecified', max_length=20)),
                ('visitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.people')),
            ],
            options={
                'verbose_name_plural': 'visitor',
            },
        ),
    ]
