# Generated by Django 4.1.4 on 2024-03-23 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit_date',
            name='dateofvisit',
            field=models.DateTimeField(default=datetime.date(2024, 3, 23)),
        ),
    ]
