# Generated by Django 4.2.15 on 2024-10-12 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visitors', '0002_visit_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='visitor_first_followup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_of_followup', models.CharField(choices=[('Whatsapp', 'Whatsapp'), ('Email', 'Email')], default='Unspecified', max_length=20)),
                ('response', models.TextField(blank=True, null=True, verbose_name='Response:')),
                ('added_to_Whatsapp_group', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=5)),
                ('date_of_followup', models.DateField(default=django.utils.timezone.now, verbose_name='Date:')),
                ('followedup_up_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors.visit_details')),
            ],
            options={
                'verbose_name_plural': 'Visitor First Follow up',
            },
        ),
    ]
