# Generated by Django 4.2.15 on 2024-10-12 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visitors', '0003_visitor_first_followup'),
    ]

    operations = [
        migrations.CreateModel(
            name='visitor_followup_call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_feedback', models.TextField(verbose_name='Feedback:')),
                ('prayer_request', models.TextField(blank=True, null=True, verbose_name='Prayer Request')),
                ('date_of_followup', models.DateField(default=django.utils.timezone.now, verbose_name='Date:')),
                ('followedup_up_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors.visit_details')),
            ],
            options={
                'verbose_name_plural': 'Visitor Follow up call',
            },
        ),
    ]
