# Generated by Django 4.2.15 on 2024-10-12 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0004_alter_prayer_cell_feedback_disciple_leader'),
        ('visitors', '0004_visitor_followup_call'),
    ]

    operations = [
        migrations.CreateModel(
            name='visitor_referral_finalize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refer_to_church', models.TextField(blank=True, null=True, verbose_name='Refer to another church:')),
                ('finalize', models.BooleanField()),
                ('date_of_followup', models.DateField(default=django.utils.timezone.now, verbose_name='Date:')),
                ('followedup_up_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('refer_to_prayer_cell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.session_attended_options')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors.visit_details')),
            ],
            options={
                'verbose_name_plural': 'Visitor Referral and Finalize',
            },
        ),
    ]
