# Generated by Django 4.1.4 on 2024-04-16 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0008_alter_visit_date_dateofvisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit_date',
            name='dateofvisit',
            field=models.DateTimeField(default=datetime.date(2024, 4, 16)),
        ),
    ]
