# Generated by Django 4.1.4 on 2024-05-29 23:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0014_alter_visit_date_dateofvisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit_date',
            name='dateofvisit',
            field=models.DateTimeField(default=datetime.date(2024, 5, 30)),
        ),
    ]
