# Generated by Django 5.0.7 on 2024-08-20 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0022_alter_visit_date_dateofvisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit_date',
            name='dateofvisit',
            field=models.DateTimeField(default=datetime.date(2024, 8, 20)),
        ),
    ]
