# Generated by Django 4.2.15 on 2024-09-03 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0023_alter_visit_date_dateofvisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit_date',
            name='dateofvisit',
            field=models.DateTimeField(default=datetime.date(2024, 9, 3)),
        ),
    ]
