# Generated by Django 4.2.15 on 2024-09-17 16:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Surname', models.CharField(max_length=20)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=7, null=True)),
                ('CellNumber', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Invalid phone number. Must be 10 digits.')], verbose_name='Cellphone Number')),
                ('EmailAddress', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email Address')),
                ('birthday', models.DateTimeField(blank=True, null=True, verbose_name='Date of Birth: (e.g. 16 March 2010)')),
                ('area', models.CharField(max_length=20, verbose_name='Area: (e.g. Ramsgate or Margate or Pretoria)')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='guardianRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians_as_child', to='people.people')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians_as_parent', to='people.people')),
            ],
        ),
        migrations.AddConstraint(
            model_name='people',
            constraint=models.UniqueConstraint(fields=('Name', 'Surname'), name='people_people_unique'),
        ),
        migrations.AddConstraint(
            model_name='guardianrelation',
            constraint=models.UniqueConstraint(fields=('child', 'parent'), name='people_guardianrelation_unique'),
        ),
    ]
