# Generated by Django 4.1.4 on 2024-07-06 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians_as_child', to='people.people')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians_as_parent', to='people.people')),
            ],
            options={
                'verbose_name_plural': 'Guardian',
            },
        ),
    ]
