# Generated by Django 4.1.4 on 2024-07-06 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_guardian'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='guardian',
            new_name='guardianRelation',
        ),
    ]
