# Generated by Django 5.0.7 on 2024-07-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_rename_guardian_guardianrelation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guardianrelation',
            options={},
        ),
        migrations.AddConstraint(
            model_name='guardianrelation',
            constraint=models.UniqueConstraint(fields=('child', 'parent'), name='people_guardianrelation_unique'),
        ),
    ]
